<?php

/*

    test/php/utils/code_test_coverage.php - list the functions with less than two unit test calls
    -------------------------------------

    creates the markdown report docs/code_test_coverage.md with all public source functions
    that are called less than twice in the unit tests of src/test/php/unit

    a function call counts as a unit test when it is between a '$test_name = ...' line
    and the last '$t->assert...' or '$this->assert...' line of the same code block,
    where a block ends at the next empty line


    This file is part of zukunft.com - calc with words

    zukunft.com is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as
    published by the Free Software Foundation, either version 3 of
    the License, or (at your option) any later version.
    zukunft.com is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with zukunft.com. If not, see <http://www.gnu.org/licenses/agpl.html>.

    To contact the authors write to:
    Timon Zielonka <timon@zukunft.com>

    Copyright (c) 1995-2026 zukunft.com AG, Zurich
    Heang Lor <heang@zukunft.com>

    http://zukunft.com

*/

namespace Zukunft\ZukunftCom\test\php\utils;

use Zukunft\ZukunftCom\main\php\cfg\const\paths;
use Zukunft\ZukunftCom\test\php\const\paths as test_paths;

include_once paths::SHARED . 'library.php';

use Zukunft\ZukunftCom\main\php\shared\library;

class code_test_coverage
{

    // the number of unit test calls every function should at least have (positive and negative test)
    const int MIN_TESTS = 2;

    // a line that starts a unit test block
    private const string TEST_NAME_PATTERN = '/\$test_name\s*=/';
    // an assert call of the test harness that ends the counted part of a test block
    private const string ASSERT_PATTERN = '/\$(t|this)\s*->\s*assert\w*\s*\(/';
    // an object function call e.g. '$wrd->save(' incl. chained calls e.g. '$sys->typ_lst->id('
    private const string CALL_PATTERN = '/(\$\w+|\w+|\))\s*->\s*(\w+)\s*\(/';
    // a static function call e.g. 'user::system('
    private const string STATIC_CALL_PATTERN = '/(\w+)::(\w+)\s*\(/';
    // a function declaration with the optional modifiers
    private const string FUNCTION_PATTERN
        = '/^\s*((?:(?:public|private|protected|static|abstract|final)\s+)*)function\s+(\w+)\s*\(/';
    // the callers of the test harness that are not source function calls
    private const array HARNESS_VARS = ['$t', '$this'];
    // the static callers that are not a class name
    private const array NO_CLASS_CALLERS = ['self', 'static', 'parent'];

    /**
     * build the markdown report of the public source functions
     * that have less than MIN_TESTS unit test calls
     *
     * @return string the markdown content for docs/code_test_coverage.md
     */
    function md(): string
    {
        $cnt_lst = $this->test_call_counts(test_paths::UNIT);
        $sec_lst = [
            'main backend' => paths::MODEL,
            'shared' => paths::SHARED,
            'frontend' => paths::WEB
        ];
        $fnc_cnt = 0;
        $low_cnt = 0;
        $body_txt = '';
        foreach ($sec_lst as $sec => $path) {
            $body_txt .= $this->section_md($sec, $path, $cnt_lst, $fnc_cnt, $low_cnt);
        }
        $md_txt = '# Unit test coverage' . "\n";
        $md_txt .= "\n";
        $md_txt .= 'generated by bin/code_test_coverage.php - do not edit manually' . "\n";
        $md_txt .= "\n";
        $md_txt .= 'a function call counts as a unit test when it is between a $test_name assignment' . "\n";
        $md_txt .= 'and the last assert of the same block (a block ends at the next empty line)' . "\n";
        $md_txt .= 'in a test file of src/test/php/unit; the count is by function name,' . "\n";
        $md_txt .= 'so same-named functions of several classes share their test calls' . "\n";
        $md_txt .= "\n";
        $md_txt .= ($fnc_cnt - $low_cnt) . ' of ' . $fnc_cnt . ' public functions have at least '
            . self::MIN_TESTS . ' unit test calls; the ' . $low_cnt . ' functions below do not' . "\n";
        $md_txt .= $body_txt;
        return $md_txt;
    }

    /**
     * build the markdown section of one source folder with one row
     * per class function that has less than MIN_TESTS unit test calls
     *
     * @param string $sec the section name e.g. 'main backend'
     * @param string $path the source folder of the section e.g. paths::MODEL
     * @param array $cnt_lst map of function name to the number of unit test calls
     * @param int $fnc_cnt (in/out) total number of public functions checked
     * @param int $low_cnt (in/out) number of functions with less than MIN_TESTS calls
     * @return string the markdown section with the class tree of the undertested functions
     */
    private function section_md(
        string $sec,
        string $path,
        array  $cnt_lst,
        int    &$fnc_cnt,
        int    &$low_cnt
    ): string
    {
        $md_txt = '';
        foreach ($this->source_functions($path) as $class => $fnc_lst) {
            $fnc_cnt += count($fnc_lst);
            $row_txt = '';
            foreach ($fnc_lst as $fnc) {
                $cnt = $cnt_lst[$fnc] ?? 0;
                if ($cnt < self::MIN_TESTS) {
                    $low_cnt++;
                    $row_txt .= '    \-- ' . $fnc . ' - ' . $cnt . ' unit test calls' . "\n";
                }
            }
            if ($row_txt != '') {
                $md_txt .= '\-- ' . $class . "\n" . $row_txt;
            }
        }
        $sec_txt = '';
        if ($md_txt != '') {
            $sec_txt = "\n" . '## ' . $sec . "\n" . "\n"
                . '```' . "\n" . $md_txt . '```' . "\n";
        }
        return $sec_txt;
    }

    /**
     * collect the public functions of every php class file below the given folder
     *
     * @param string $path the source folder to scan recursively e.g. paths::MODEL
     * @return array map of class name to its sorted list of public function names
     */
    private function source_functions(string $path): array
    {
        $lib = new library();
        $result = [];
        foreach ($lib->array_to_path($lib->dir_to_array($path)) as $code_file) {
            if (str_ends_with($code_file, '.php')) {
                $lines = file($path . $code_file);
                $class = $lib->php_class_from_code($lines);
                if ($class == '') {
                    // a file without a class e.g. text_log_functions.php is grouped by its file name
                    $class = basename($code_file, '.php');
                }
                $fnc_lst = array_merge($result[$class] ?? [], $this->public_functions($lines));
                if ($fnc_lst != []) {
                    $result[$class] = $fnc_lst;
                }
            }
        }
        foreach ($result as $class => $fnc_lst) {
            $fnc_lst = array_unique($fnc_lst);
            sort($fnc_lst, SORT_STRING);
            $result[$class] = $fnc_lst;
        }
        ksort($result, SORT_STRING);
        return $result;
    }

    /**
     * collect the public function names declared in one php file;
     * private and protected functions are skipped because a unit test cannot call them
     * and the magic functions e.g. __construct because they are never called with '->name('
     *
     * @param array $lines the code lines of the php file
     * @return array list of the public function names
     */
    private function public_functions(array $lines): array
    {
        $result = [];
        foreach ($lines as $line) {
            $hit = [];
            if (preg_match(self::FUNCTION_PATTERN, $line, $hit)) {
                $hidden = str_contains($hit[1], 'private') || str_contains($hit[1], 'protected');
                if (!$hidden and !str_starts_with($hit[2], '__')) {
                    $result[] = $hit[2];
                }
            }
        }
        return $result;
    }

    /**
     * count per function name how often it is called in the unit test blocks
     * of all test files below the given folder
     *
     * @param string $path the unit test folder to scan e.g. test_paths::UNIT
     * @return array map of function name to the number of unit test calls
     */
    private function test_call_counts(string $path): array
    {
        $lib = new library();
        $result = [];
        foreach ($lib->array_to_path($lib->dir_to_array($path)) as $code_file) {
            if (str_ends_with($code_file, '.php')) {
                $lines = file($path . $code_file);
                // empty sentinel line to close a block at the file end
                $lines[] = '';
                $block = [];
                foreach ($lines as $line) {
                    if (trim($line) == '') {
                        $this->count_block_calls($block, $result);
                        $block = [];
                    } elseif ($block != [] or preg_match(self::TEST_NAME_PATTERN, $line)) {
                        $block[] = $line;
                    }
                }
            }
        }
        return $result;
    }

    /**
     * count the function calls of one unit test block: all object and static calls
     * from the '$test_name = ...' start line up to the last assert line are counted;
     * a block without an assert counts nothing
     *
     * @param array $block the code lines from the '$test_name = ...' line to the empty line
     * @param array $cnt_lst (in/out) map of function name to the number of unit test calls
     * @return void
     */
    private function count_block_calls(array $block, array &$cnt_lst): void
    {
        $end = -1;
        foreach ($block as $i => $line) {
            if (preg_match(self::ASSERT_PATTERN, $line)) {
                $end = $i;
            }
        }
        for ($i = 0; $i <= $end; $i++) {
            $hits = [];
            preg_match_all(self::CALL_PATTERN, $block[$i], $hits, PREG_SET_ORDER);
            foreach ($hits as $hit) {
                if (!in_array($hit[1], self::HARNESS_VARS)) {
                    $cnt_lst[$hit[2]] = ($cnt_lst[$hit[2]] ?? 0) + 1;
                }
            }
            preg_match_all(self::STATIC_CALL_PATTERN, $block[$i], $hits, PREG_SET_ORDER);
            foreach ($hits as $hit) {
                if (!in_array($hit[1], self::NO_CLASS_CALLERS)) {
                    $cnt_lst[$hit[2]] = ($cnt_lst[$hit[2]] ?? 0) + 1;
                }
            }
        }
    }

}