<?php

/*

    test/php/utils/json_validation.php - check the import json files against the json rules
    ----------------------------------

    the checks of coding_rule_tests that judge an import json are collected here, so that
    they can be used by the coding rule test (which asserts that no file breaks a rule) and
    by test/json_validation.php (which lists every finding per file in docs/json_findings.md)

    the folders are scanned with a directory iterator and never with a list of file consts,
    so a json file added later is checked without changing any code


    This file is part of zukunft.com - calc with words

    zukunft.com is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as
    published by the Free Software Foundation, either version 3 of
    the License, or (at your option) any later version.
    zukunft.com is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with zukunft.com. If not, see <http://www.gnu.org/licenses/agpl.html>.

    To contact the authors write to:
    Timon Zielonka <timon@zukunft.com>

    Copyright (c) 1995-2026 zukunft.com AG, Zurich
    Heang Lor <heang@zukunft.com>

    http://zukunft.com

*/

namespace Zukunft\ZukunftCom\test\php\utils;

use Zukunft\ZukunftCom\main\php\cfg\const\paths;
use Zukunft\ZukunftCom\test\php\const\paths as test_paths;

include_once paths::MODEL_CONST . 'def.php';
include_once paths::SHARED_CONST . 'files.php';
include_once paths::SHARED . 'json_fields.php';
include_once paths::SHARED . 'library.php';

use Zukunft\ZukunftCom\main\php\cfg\const\def;
use Zukunft\ZukunftCom\main\php\shared\const\files;
use Zukunft\ZukunftCom\main\php\shared\json_fields;
use Zukunft\ZukunftCom\main\php\shared\library;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use ReflectionClass;

class json_validation
{

    // the folders with the import json files: the productive import data and the test imports
    const array SCAN_PATHS = [
        'import data' => files::MESSAGE_PATH,
        'test import' => test_paths::IMPORT,
    ];

    // the qualifier that only repeats the default, see docs/llm/json_structure.md
    const string MEASURED_VALUE = 'measured value';

    // the deviation from the default that is worth recording, so it may be a multi word name
    const string ASSUMED_VALUE = 'assumed value';

    // the max length of a lower case word that can be part of a proper noun e.g. "and" or "de"
    const int CONNECTOR_LENGTH = 3;

    // the max length of the sample of a finding, so that one finding stays on one report line
    const int SAMPLE_LENGTH = 120;

    // the check names used as the section names of the report
    const string CHK_SYNTAX = 'not a valid json';
    const string CHK_MEASURED = 'measured value qualifier';
    const string CHK_VERB = 'verb not defined';
    const string CHK_FIELD = 'field not read by the import';
    const string CHK_WORD_SPACE = 'word with a space';
    const string CHK_VERSION = 'format version';


    /*
     * report
     */

    /**
     * build the markdown report of all findings of all import json files
     *
     * @param bool $update true to write the format version and the data version into the files
     *                     that have no other finding, false to only report what would change
     * @return string the markdown content for docs/json_findings.md
     */
    function md(bool $update = false): string
    {
        $find_lst = $this->findings($update);
        $file_cnt = 0;
        foreach (self::SCAN_PATHS as $path) {
            $file_cnt += count($this->json_file_list($path));
        }

        $md_txt = '# Json findings' . "\n";
        $md_txt .= "\n";
        $md_txt .= 'generated by test/json_validation.php - do not edit manually' . "\n";
        $md_txt .= "\n";
        $md_txt .= 'the import json rules are described in docs/llm/json_structure.md;'
            . ' the checks are the same as in coding_rule_tests, but listed per file here' . "\n";
        $md_txt .= "\n";
        $md_txt .= $file_cnt . ' json files checked, '
            . $this->hit_count($find_lst) . ' findings' . "\n";

        $md_txt .= $this->section_md(self::CHK_SYNTAX, $find_lst,
            'a file that cannot be decoded is skipped by every other check,'
            . ' so it is imported as an empty message without any warning');
        $md_txt .= $this->section_md(self::CHK_MEASURED, $find_lst,
            'every value is assumed to be measured, so the qualifier only repeats the default'
            . ' while it lengthens the phrase group and needs a word or triple in every file'
            . ' that borrows it; only the deviation "assumed value" is worth recording');
        $md_txt .= $this->section_md(self::CHK_VERB, $find_lst,
            'the import resolves a verb by an exact name match and creates the verb when the name'
            . ' is unknown (see triple::import_mapper), so a typo silently grows the shared verb'
            . ' vocabulary; a file may propose its own verb in its "verbs" section');
        $md_txt .= $this->section_md(self::CHK_FIELD, $find_lst,
            'the import mapper reads a field by its json_fields const, so a field name that is'
            . ' not one of them is silently dropped: the data of the field is never imported and'
            . ' nothing is reported, because an unknown key is simply not looked at; checked are'
            . ' the top level keys and the keys of the entries of a top level list');
        $md_txt .= $this->section_md(self::CHK_WORD_SPACE, $find_lst,
            'a word is the smallest reusable unit of meaning, so a name with a space usually'
            . ' hides a composition that belongs in a triple: define the single word atoms and'
            . ' join them e.g. {from: "textbook", verb: "of", to: "economics"}; an external'
            . ' proper noun (Burkina Faso) keeps its space and is not listed here');
        $md_txt .= $this->section_md(self::CHK_VERSION, $find_lst,
            '"version" is the version of the json format and not of the data, so it is matched'
            . ' against def::PRG_VERSION ("' . def::PRG_VERSION . '"); a file that is behind is'
            . ' raised to it, a file that is ahead is only reported, because its data may need a'
            . ' newer program; the data version is the version of the content of the file and is'
            . ' raised by the author with every data change');
        return $md_txt;
    }

    /**
     * check every json file of the scanned folders
     *
     * @param bool $update true to write the version fields of the files without another finding
     * @return array map of the check name and the scanned folder to the sorted findings, so that
     *               the folder is named once in the report and not in front of every file
     */
    function findings(bool $update = false): array
    {
        $result = [];
        foreach (self::SCAN_PATHS as $sec => $path) {
            foreach ($this->json_file_list($path) as $file_path) {
                $this->check_file($sec, $file_path, $result, $update);
            }
        }
        foreach ($result as $chk => $sec_lst) {
            foreach ($sec_lst as $sec => $hits) {
                sort($hits);
                $result[$chk][$sec] = $hits;
            }
        }
        return $result;
    }

    /**
     * check one json file and add each finding to the given list
     *
     * @param string $sec the name of the scanned folder e.g. 'test import'
     * @param string $file_path the json file to check
     * @param array $find_lst (in/out) map of the check name and the folder to the findings
     * @param bool $update true to write the version fields if no other check has a finding
     * @return void
     */
    private function check_file(string $sec, string $file_path, array &$find_lst, bool $update): void
    {
        $name = basename($file_path);
        $json_array = json_decode(file_get_contents($file_path), true);
        if (!is_array($json_array)) {
            $find_lst[self::CHK_SYNTAX][$sec][] = $name . ' - ' . json_last_error_msg();
        } else {
            $clean = true;
            foreach ($this->measured_value_hits($json_array) as $sec_name => $sample) {
                $find_lst[self::CHK_MEASURED][$sec][] = $name . ' (' . $sec_name . ') - ' . $sample;
                $clean = false;
            }
            foreach ($this->verb_undefined_hits($json_array) as $verb_name => $sample) {
                $find_lst[self::CHK_VERB][$sec][] = $name . ' - "' . $verb_name . '" in ' . $sample;
                $clean = false;
            }
            foreach ($this->field_unknown_hits($json_array) as $fld_name => $sample) {
                $find_lst[self::CHK_FIELD][$sec][] = $name . ' - ' . $fld_name . ' - ' . $sample;
                $clean = false;
            }
            foreach ($this->word_space_hits($json_array) as $wrd_name => $sample) {
                $find_lst[self::CHK_WORD_SPACE][$sec][] = $name . ' - ' . $wrd_name . ' - ' . $sample;
                $clean = false;
            }
            // the version is checked last, because a file with a finding is not yet in the
            // format of this program version, so raising its version would hide the finding
            if ($clean) {
                $hit = $this->version_hit($file_path, $json_array, $update);
                if ($hit != '') {
                    $find_lst[self::CHK_VERSION][$sec][] = $name . ' - ' . $hit;
                }
            }
        }
    }


    /*
     * check
     */

    /**
     * the places where the "measured value" qualifier can hide: as a value or calc-validation
     * qualifier and as the word or triple that such a qualifier needs
     *
     * @param array $json_array the decoded json file
     * @return array map of the section that uses the qualifier to the first entry that uses it,
     *               so that the report can show what to fix and the caller can use the keys only
     */
    function measured_value_hits(array $json_array): array
    {
        $hits = [];
        foreach ($json_array[json_fields::VALUES] ?? [] as $val) {
            if (in_array(self::MEASURED_VALUE, $val[json_fields::WORDS] ?? [], true)) {
                $hits['value'] ??= $this->sample($val);
            }
        }
        foreach ($json_array[json_fields::CALC_VALIDATION] ?? [] as $calc) {
            foreach ([json_fields::CONTEXT, json_fields::WORDS] as $fld) {
                if (in_array(self::MEASURED_VALUE, $calc[$fld] ?? [], true)) {
                    $hits['calc-validation'] ??= $this->sample($calc);
                }
            }
        }
        foreach ($json_array[json_fields::WORDS] ?? [] as $wrd) {
            if (($wrd[json_fields::NAME] ?? '') == self::MEASURED_VALUE) {
                $hits['word'] ??= $this->sample($wrd);
            }
        }
        foreach ($json_array[json_fields::TRIPLES] ?? [] as $trp) {
            foreach ([json_fields::NAME, json_fields::EX_FROM, json_fields::EX_TO] as $fld) {
                if (($trp[$fld] ?? '') == self::MEASURED_VALUE) {
                    $hits['triple'] ??= $this->sample($trp);
                }
            }
        }
        return $hits;
    }

    /**
     * the verbs that the triples of the given file use without a definition
     *
     * @param array $json_array the decoded json file
     * @return array map of the verb name that is neither in verbs.json nor proposed by the file
     *               to the first triple that uses it, see measured_value_hits
     */
    function verb_undefined_hits(array $json_array): array
    {
        $known = $this->verbs_known();
        // a file may propose its own verb, which stays private until an admin confirms it
        foreach ($json_array[json_fields::VERBS] ?? [] as $vrb) {
            $known[$vrb[json_fields::NAME] ?? ''] = true;
        }
        $unknown = [];
        foreach ($json_array[json_fields::TRIPLES] ?? [] as $trp) {
            $name = $trp[json_fields::EX_VERB] ?? '';
            if ($name != '' and !array_key_exists($name, $known)) {
                $unknown[$name] ??= $this->sample($trp);
            }
        }
        return $unknown;
    }

    /**
     * the word names of the given file that contain a space
     *
     * a word is the most atomic text of the graph, so a composition like "economics textbook"
     * belongs in a triple that joins the single word atoms (docs/llm/json_structure.md);
     * the documented exceptions are not reported: an external proper noun that is written with
     * a space in the real world and the "assumed value" qualifier
     *
     * @param array $json_array the decoded json file
     * @return array map of the word name with a space to the first word entry that uses it
     */
    function word_space_hits(array $json_array): array
    {
        $hits = [];
        foreach ($json_array[json_fields::WORDS] ?? [] as $wrd) {
            if (is_array($wrd)) {
                $name = $wrd[json_fields::NAME] ?? '';
                if (is_string($name) and str_contains(trim($name), ' ')) {
                    if ($name != self::ASSUMED_VALUE and !$this->is_proper_noun($name)) {
                        $hits['"' . $name . '"'] ??= $this->sample($wrd);
                    }
                }
            }
        }
        return $hits;
    }

    /**
     * a name is treated as an external proper noun if it is written like one: it starts with an
     * upper case letter and every following word is upper case too, a short connector ("and",
     * "de"), a name with an apostrophe ("d'Ivoire") or a parenthetical of an official name
     * ("Cocos (Keeling) Islands"); a lower case start like "second (time)" is never a proper noun
     *
     * @param string $name the word name to judge
     * @return bool true if the space of the name is expected
     */
    private function is_proper_noun(string $name): bool
    {
        $tok_lst = explode(' ', trim($name));
        $result = $this->starts_upper(array_shift($tok_lst));
        foreach ($tok_lst as $tok) {
            if (!$this->starts_upper($tok)
                and strlen($tok) > self::CONNECTOR_LENGTH
                and !str_contains($tok, "'")
                and !str_starts_with($tok, '(')) {
                $result = false;
            }
        }
        return $result;
    }

    /**
     * the first byte and not mb_substr, so that the check also runs where mbstring is missing;
     * a name that starts with a multi byte char is treated as upper case, which is the safe
     * default for a proper noun like "Ãlysee"
     *
     * @param string $txt the text to check
     * @return bool true if the text starts with an upper case letter
     */
    private function starts_upper(string $txt): bool
    {
        $chr = substr($txt, 0, 1);
        return $chr != '' and $chr == strtoupper($chr);
    }

    /**
     * check the format version and the data version of a file that has no other finding
     *
     * "version" names the version of the json format, so it is matched against the program
     * version; a file that is behind is raised, because the format has been migrated with the
     * program, and a file that is ahead is only reported, because its data may need a program
     * that is not yet installed (this is what msg_id::IMPORT_VERSION_NEWER warns about)
     *
     * @param string $file_path the json file to check
     * @param array $json_array the decoded json file
     * @param bool $update true to write the missing or outdated versions into the file
     * @return string the finding or an empty string if both versions are as expected
     */
    private function version_hit(string $file_path, array $json_array, bool $update): string
    {
        $lib = new library();
        $result = '';
        $version = $json_array[json_fields::VERSION] ?? '';
        $data_version = $json_array[json_fields::DATA_VERSION] ?? '';
        if ($version == '') {
            // where to add the field cannot be guessed, because the header may be missing at all
            $result = 'no "' . json_fields::VERSION . '" field';
        } elseif ($lib->prg_version_is_newer($version)) {
            $result = 'format version "' . $version . '" is newer than the program version "'
                . def::PRG_VERSION . '", so it is not changed';
        } else {
            if ($version != def::PRG_VERSION) {
                $result = 'format version "' . $version . '" raised to "' . def::PRG_VERSION . '"';
            }
            if ($data_version == '') {
                $add_txt = 'no "' . json_fields::DATA_VERSION . '" field, so "'
                    . def::DATA_VERSION_INIT . '" added';
                $result = $result == '' ? $add_txt : $result . ', ' . $add_txt;
            }
            if ($result != '' and $update) {
                $this->version_update($file_path, $version, $data_version);
            } elseif ($result != '') {
                $result .= ' (dry run)';
            }
        }
        return $result;
    }

    /**
     * write the program version as the format version into the file and add the initial data
     * version if the file has none
     *
     * only the version lines are replaced and never the complete json, because rewriting the
     * file with json_encode would reformat every line and destroy the review of the real change
     *
     * @param string $file_path the json file to update
     * @param string $version the format version that the file has now
     * @param string $data_version the data version that the file has now or an empty string
     * @return void
     */
    private function version_update(string $file_path, string $version, string $data_version): void
    {
        $txt = file_get_contents($file_path);
        $old_line = '"' . json_fields::VERSION . '": "' . $version . '"';
        $new_line = '"' . json_fields::VERSION . '": "' . def::PRG_VERSION . '"';
        if ($data_version == '') {
            $new_line .= ',' . "\n" . $this->line_indent($txt, $old_line)
                . '"' . json_fields::DATA_VERSION . '": "' . def::DATA_VERSION_INIT . '"';
        }
        // only the first hit, because a value or a source of the file may name a version too
        $pos = strpos($txt, $old_line . ',');
        if ($pos !== false) {
            $txt = substr_replace($txt, $new_line . ',', $pos, strlen($old_line) + 1);
            file_put_contents($file_path, $txt);
        }
    }

    /**
     * @param string $txt the complete file text
     * @param string $line the line content to find
     * @return string the whitespace in front of the given line content
     */
    private function line_indent(string $txt, string $line): string
    {
        $lib = new library();
        $before = $lib->str_left_of($txt, $line);
        $last_line = substr($before, strrpos($before, "\n") + 1);
        return str_repeat(' ', strlen($last_line));
    }

    /**
     * the first entry that breaks a rule, short enough for one report line
     *
     * @param array $entry the json entry e.g. the value or the triple that has the finding
     * @return string the entry as a json string, cut after SAMPLE_LENGTH chars
     */
    private function sample(array $entry): string
    {
        $lib = new library();
        $result = json_encode($entry);
        if (strlen($result) > self::SAMPLE_LENGTH) {
            $result = $lib->str_left($result, self::SAMPLE_LENGTH) . ' ...';
        }
        return $result;
    }

    /**
     * the fields of the given file that the import mapper does not read
     *
     * every field that an import mapper reads is a const of json_fields, so a key that is not
     * one of them is dropped without any message: array_key_exists simply never matches it
     *
     * checked are the top level keys and the keys of the entries of a top level list, because
     * that is where the mappers read named fields; a deeper structure can use data as keys
     * (e.g. a compact value list), which would create false positives
     *
     * @param array $json_array the decoded json file
     * @return array map of the section and the unknown field to the first entry that uses it
     */
    function field_unknown_hits(array $json_array): array
    {
        $known = $this->fields_known();
        $hits = [];
        foreach ($json_array as $key => $value) {
            if (!array_key_exists($key, $known)) {
                $hits['top level: "' . $key . '"'] ??= $this->sample([$key => $value]);
            }
            if (is_array($value)) {
                $this->entry_field_hits($key, $value, $known, $hits);
            }
        }
        return $hits;
    }

    /**
     * add the unknown fields of the entries of one top level list to the given hit list
     *
     * @param string $sec_name the name of the top level list e.g. 'values'
     * @param array $entry_lst the entries of the top level list
     * @param array $known the field names that an import mapper reads as the keys
     * @param array $hits (in/out) map of the section and the unknown field to the first sample
     * @return void
     */
    private function entry_field_hits(
        string $sec_name,
        array  $entry_lst,
        array  $known,
        array  &$hits
    ): void
    {
        foreach ($entry_lst as $entry) {
            if (is_array($entry)) {
                foreach ($entry as $fld => $val) {
                    if (is_string($fld) and !array_key_exists($fld, $known)) {
                        $hits[$sec_name . ': "' . $fld . '"'] ??= $this->sample($entry);
                    }
                }
            }
        }
    }

    /**
     * @return array the field names that an import mapper can read as the keys
     */
    private function fields_known(): array
    {
        $result = [];
        $fld_lst = new ReflectionClass(json_fields::class)->getConstants();
        foreach ($fld_lst as $fld) {
            if (is_string($fld)) {
                $result[$fld] = true;
            }
        }
        return $result;
    }

    /**
     * @return array the verb names of src/main/resources/verbs.json as the keys
     */
    private function verbs_known(): array
    {
        $result = [];
        $verbs_json = json_decode(file_get_contents(files::VERBS), true) ?? [];
        foreach ($verbs_json[json_fields::VERBS] ?? [] as $vrb) {
            $result[$vrb[json_fields::NAME]] = true;
        }
        return $result;
    }


    /*
     * internal
     */

    /**
     * build the markdown section of one check with one sub section per scanned folder
     *
     * the folder is the sub section headline and not a prefix of every line, so that a file
     * name is not lost in a repeated 'import data: ' and a folder without a finding is silent
     *
     * @param string $chk the check name e.g. 'verb not defined'
     * @param array $find_lst map of the check name and the folder to its findings
     * @param string $explain the one line why the findings of this check matter
     * @return string the markdown section or an empty string if the check has no finding
     */
    private function section_md(string $chk, array $find_lst, string $explain): string
    {
        $sec_txt = '';
        $sec_lst = $find_lst[$chk] ?? [];
        if ($sec_lst != []) {
            $sec_txt = "\n" . '## ' . $chk . "\n" . "\n" . $explain . "\n";
            // the scan order and not the hit order, so that the report is stable
            foreach (array_keys(self::SCAN_PATHS) as $sec) {
                $sec_txt .= $this->folder_md($sec, $sec_lst[$sec] ?? []);
            }
        }
        return $sec_txt;
    }

    /**
     * @param string $sec the name of the scanned folder e.g. 'test import'
     * @param array $hits the findings of this check in this folder
     * @return string the markdown sub section or an empty string if the folder has no finding
     */
    private function folder_md(string $sec, array $hits): string
    {
        $sec_txt = '';
        if ($hits != []) {
            $row_txt = '';
            foreach ($hits as $hit) {
                $row_txt .= $hit . "\n";
            }
            $sec_txt = "\n" . '### ' . $sec . "\n" . "\n"
                . '```' . "\n" . $row_txt . '```' . "\n";
        }
        return $sec_txt;
    }

    /**
     * @param array $find_lst map of the check name to its findings
     * @return int the total number of findings of all checks
     */
    function hit_count(array $find_lst): int
    {
        $result = 0;
        foreach ($find_lst as $sec_lst) {
            foreach ($sec_lst as $hits) {
                $result += count($hits);
            }
        }
        return $result;
    }

    /**
     * @param string $path the folder to scan for json import files
     * @return array the path of every json file below the given folder
     */
    function json_file_list(string $path): array
    {
        $result = [];
        $dir_iterator = new RecursiveDirectoryIterator($path);
        foreach (new RecursiveIteratorIterator($dir_iterator) as $file) {
            if (str_ends_with($file->getFilename(), files::JSON)) {
                $result[] = $file->getPathname();
            }
        }
        sort($result);
        return $result;
    }

}