<?php

/*

    model/system/job_cache_refresh.php - the proactive cache refresh sweep backend job
    ----------------------------------

    $job_refresh is the suggested var name

    check the system-wide config and type caches and invalidate the outdated ones, so that the next
    user request regenerates a fresh entry and hits a warm cache instead of a cold one; the reactive
    cache updates triggered by a single user request stay out of this sweep (see docs/llm/pending.md)

    the html page cache (db_cache_page) is regenerated by the frontend and is not swept here, because
    the re-render logic lives in the web frontend and must not be called from a backend job


    This file is part of zukunft.com - calc with words

    zukunft.com is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as
    published by the Free Software Foundation, either version 3 of
    the License, or (at your option) any later version.
    zukunft.com is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with zukunft.com. If not, see <http://www.gnu.org/licenses/agpl.html>.

    To contact the authors write to:
    Timon Zielonka <timon@zukunft.com>

    Copyright (c) 1995-2026 zukunft.com AG, Zurich
    Heang Lor <heang@zukunft.com>

    http://zukunft.com

*/

namespace Zukunft\ZukunftCom\main\php\cfg\system;

use Zukunft\ZukunftCom\main\php\cfg\const\paths;

include_once paths::MODEL_SYSTEM . 'job_exe.php';
include_once paths::MODEL_HELPER . 'db_cache.php';
include_once paths::MODEL_USER . 'user.php';
include_once paths::MODEL_USER . 'user_message.php';
include_once paths::SHARED_TYPES . 'db_cache_types.php';
include_once paths::SHARED_TYPES . 'job_types.php';

use Zukunft\ZukunftCom\main\php\cfg\helper\db_cache;
use Zukunft\ZukunftCom\main\php\cfg\user\user;
use Zukunft\ZukunftCom\main\php\cfg\user\user_message;
use Zukunft\ZukunftCom\main\php\shared\types\db_cache_types;
use Zukunft\ZukunftCom\main\php\shared\types\job_types;

class job_cache_refresh implements job_exe
{

    /*
     * const
     */

    // the system-wide caches that the sweep checks for freshness; the per-user caches are left to
    // the reactive update of the owning user's request and the html page cache to the frontend
    const array SWEEP_TYPES = [
        db_cache_types::SYSTEM_CONFIG,
        db_cache_types::TYPES,
        db_cache_types::FRONTEND_CONFIG,
    ];


    /*
     * interface
     */

    /**
     * @return string the code id of the job type this handler executes
     */
    function type_code_id(): string
    {
        return job_types::CACHE_REFRESH;
    }

    /**
     * invalidate every outdated system cache so the next request regenerates a fresh, warm entry
     * @param user_message $msg the message buffer that collects a delete problem for the log
     * @return int the number of caches that have been invalidated
     */
    function execute(user_message $msg): int
    {
        $result = 0;
        $usr = user::system();

        foreach (self::SWEEP_TYPES as $type_code_id) {
            $invalidated = $this->invalidate_if_outdated($type_code_id, $usr, $msg);
            if ($invalidated) {
                $result++;
            }
        }

        return $result;
    }


    /*
     * internal
     */

    /**
     * delete the current cache entry of the given type if it is outdated
     * a deleted cache entry is not lost data, because it is regenerated from the database on the next read
     * @param string $type_code_id the code id of the cache type to check e.g. db_cache_types::TYPES
     * @param user $usr the system user that loads and deletes the cache entry
     * @param user_message $msg the message buffer that collects a delete problem for the log
     * @return bool true if an outdated cache entry has been invalidated
     */
    private function invalidate_if_outdated(string $type_code_id, user $usr, user_message $msg): bool
    {
        $result = false;
        $cac = new db_cache($usr);
        $id = $cac->load_by_type($type_code_id, $msg);
        if ($id > 0 and $cac->is_outdated()) {
            $result = $cac->del($msg);
        }
        return $result;
    }

}
