PREPARE user_by_email FROM
   'SELECT user_id,
           user_name,
           ip_address,
           email,
           password,
           activation_key,
           activation_timeout,
           last_login,
           last_logoff,
           user_profile_id,
           code_id,
           user_type_id,
           right_level,
           user_status_id,
           excluded,
           created,
           description,
           first_name,
           last_name,
           term_id,
           view_id,
           source_id
      FROM users
     WHERE email = ?';